version: '3.8'

services:
  # 1. Database cho Identity & Accounting (PostgreSQL)
  postgres_db:
    image: postgres:15-alpine
    container_name: bizflow_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: bizflow_identity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bizflow-network

  # 2. Database cho Product & Order (MySQL)
  mysql_db:
    image: mysql:8.0
    container_name: bizflow_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bizflow_catalog_db
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - bizflow-network

  # 3. Redis Cache (Dùng chung)
  redis_cache:
    image: redis:alpine
    container_name: bizflow_redis
    ports:
      - "6379:6379"
    networks:
      - bizflow-network

  # 4. UI quản lý Database (Adminer - Tùy chọn, để xem DB trên web cho tiện)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - bizflow-network

  # 5. AI Service (Python FastAPI)
  ai_service:
    build:
      context: ./src/Services/BizFlow.AI
      dockerfile: Dockerfile
    container_name: bizflow_ai
    ports:
      - "5005:8000"
    volumes:
      - ./src/Services/BizFlow.AI:/app
    networks:
      - bizflow-network
    environment:
      - CHROMA_HOST=bizflow_chroma  # Tên service chroma vừa khai báo 
      - CHROMA_PORT=8000
    depends_on:
      - chroma_db

  # 6. ChromaDB (Vector Database cho AI)
  chroma_db:
    image: chromadb/chroma:latest
    container_name: bizflow_chroma
    ports:
      - "8001:8000" # Map ra port 8001 máy ngoài để bạn dễ debug
    volumes:
      - chroma_data:/chroma/chroma # Lưu dữ liệu bền vững
    networks:
      - bizflow-network

networks:
  bizflow-network:
    driver: bridge

volumes:
  pgdata:
  mysqldata:
  chroma_data: