name: bizflow_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.6.0
  intl: ^0.18.0
  pdf: ^3.10.0
  printing: ^5.11.0
  signalr_core: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  record: ^6.0.0
  permission_handler: ^12.0.1
  file_picker: ^8.0.7
  cached_network_image: ^3.4.0
  flutter_spinkit: ^5.2.2
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  fl_chart: ^1.1.1
  
  # --- THƯ VIỆN RIVERPOD (Đã gộp vào đây) ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  # Thêm thư viện này
  json_annotation: ^4.8.1
  chopper: ^7.1.1
  logging: ^1.2.0
  shared_preferences: ^2.5.4
  get_it: ^9.2.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Thêm các thư viện tạo code này
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  chopper_generator: ^7.1.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true